#!/bin/sh
# Xcode Cloud: write gitignored Release secrets from workflow Environment Variables
# so FITLOG_PROXY_SHARED_SECRET expands into Info.plist at archive time.
#
# App Store Connect → your app → Xcode Cloud → workflow → Environment
#   Name:  FITLOG_PROXY_SHARED_SECRET
#   Value: same secret as Render
#   Secret: ON
#
# Docs: docs/SHIP_CHECKLIST.md §2b-2

set -euo pipefail

REPO_ROOT="${CI_PRIMARY_REPOSITORY_PATH:-$(cd "$(dirname "$0")/.." && pwd)}"
SECRETS_FILE="${REPO_ROOT}/Config/Secrets.release.xcconfig"

if [ -z "${FITLOG_PROXY_SHARED_SECRET:-}" ]; then
  # Test / build-for-testing do not expand Release Info.plist; skip instead of failing the suite.
  # Archive/build still require the secret so TestFlight never ships without proxy auth.
  case "${CI_XCODEBUILD_ACTION:-}" in
    test|build-for-testing|test-without-building)
      echo "warning: FITLOG_PROXY_SHARED_SECRET unset; skipping Secrets.release.xcconfig for ${CI_XCODEBUILD_ACTION}."
      exit 0
      ;;
  esac
  echo "error: FITLOG_PROXY_SHARED_SECRET is not set in Xcode Cloud Environment."
  echo "error: Refusing to archive without proxy auth — Premium AI / form guide would 401."
  echo "error: App Store Connect → Xcode Cloud → workflow → Environment → add FITLOG_PROXY_SHARED_SECRET (Secret ON)."
  exit 1
fi

# xcconfig: unquoted values with special chars can break parsing; keep secret alphanumeric/hex.
cat > "${SECRETS_FILE}" <<EOF
// Generated by ci_scripts/ci_pre_xcodebuild.sh — do not commit.
FITLOG_PROXY_SHARED_SECRET = ${FITLOG_PROXY_SHARED_SECRET}
EOF

echo "Wrote Config/Secrets.release.xcconfig for Release Info.plist expansion (secret length=${#FITLOG_PROXY_SHARED_SECRET})."
