#!/bin/sh
# Xcode Cloud: write gitignored Release secrets from workflow Environment Variables
# so FITLOG_PROXY_SHARED_SECRET expands into Info.plist at archive time.
#
# App Store Connect → your app → Xcode Cloud → workflow → Environment
#   Name:  FITLOG_PROXY_SHARED_SECRET
#   Value: same secret as Render
#   Secret: ON
#   Scope: Archive (required). Other actions may omit it.
#
# Docs: docs/SHIP_CHECKLIST.md §2b-2

set -euo pipefail

REPO_ROOT="${CI_PRIMARY_REPOSITORY_PATH:-$(cd "$(dirname "$0")/.." && pwd)}"
SECRETS_FILE="${REPO_ROOT}/Config/Secrets.release.xcconfig"
ACTION="${CI_XCODEBUILD_ACTION:-}"

if [ -z "${FITLOG_PROXY_SHARED_SECRET:-}" ]; then
  # Only Archive ships a binary that must carry proxy auth. Test/Build often leave
  # this ASC secret scoped off. When CI_XCODEBUILD_ACTION is empty we cannot tell
  # archive from other actions — fail closed so a mis-scoped secret cannot ship.
  case "${ACTION}" in
    archive|"")
      echo "error: FITLOG_PROXY_SHARED_SECRET is not set in Xcode Cloud Environment."
      echo "error: Refusing to archive without proxy auth — Premium AI / form guide would 401."
      echo "error: App Store Connect → Xcode Cloud → workflow → Environment → add FITLOG_PROXY_SHARED_SECRET (Secret ON)."
      exit 1
      ;;
  esac
  echo "warning: FITLOG_PROXY_SHARED_SECRET unset; skipping Secrets.release.xcconfig for action='${ACTION}'."
  exit 0
fi

# xcconfig: unquoted values with special chars can break parsing; keep secret alphanumeric/hex.
cat > "${SECRETS_FILE}" <<EOF
// Generated by ci_scripts/ci_pre_xcodebuild.sh — do not commit.
FITLOG_PROXY_SHARED_SECRET = ${FITLOG_PROXY_SHARED_SECRET}
EOF

echo "Wrote Config/Secrets.release.xcconfig for Release Info.plist expansion (secret length=${#FITLOG_PROXY_SHARED_SECRET})."
