#!/bin/bash
# Xcode Cloud: write gitignored Release secrets from workflow Environment Variables
# so FITLOG_PROXY_SHARED_SECRET expands into Info.plist at archive time.
#
# App Store Connect → your app → Xcode Cloud → workflow → Environment
#   Name:  FITLOG_PROXY_SHARED_SECRET
#   Value: same secret as Render
#   Secret: ON
#   Scope: Archive (required for TestFlight). Other actions may omit it.
#
# Docs: docs/SHIP_CHECKLIST.md §2b-2
#
# This script must not fail non-archive actions: ASC often scopes the secret to
# Archive only, and CI_XCODEBUILD_ACTION is not always reliable in pre-scripts.

set +e

REPO_ROOT="${CI_PRIMARY_REPOSITORY_PATH:-}"
if [ -z "${REPO_ROOT}" ]; then
  REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
fi
if [ -z "${REPO_ROOT}" ]; then
  echo "error: could not resolve repository root (CI_PRIMARY_REPOSITORY_PATH unset and fallback cd failed)"
  exit 1
fi
SECRETS_FILE="${REPO_ROOT}/Config/Secrets.release.xcconfig"
ACTION="${CI_XCODEBUILD_ACTION:-}"
SECRET_PRESENT=0
if [ -n "${FITLOG_PROXY_SHARED_SECRET:-}" ]; then
  SECRET_PRESENT=1
fi

echo "ci_pre_xcodebuild: action='${ACTION:-<empty>}' secret_present=${SECRET_PRESENT} repo='${REPO_ROOT}'"

if [ "${SECRET_PRESENT}" -eq 0 ]; then
  echo "warning: FITLOG_PROXY_SHARED_SECRET unset; skipping Secrets.release.xcconfig for action='${ACTION:-<empty>}'."
  if [ "${ACTION}" = "archive" ]; then
    echo "error: Archive is missing FITLOG_PROXY_SHARED_SECRET — TestFlight Premium AI would 401."
    echo "error: App Store Connect → Xcode Cloud → workflow → Environment → add FITLOG_PROXY_SHARED_SECRET (Secret ON) for Archive."
    exit 1
  fi
  exit 0
fi

mkdir -p "${REPO_ROOT}/Config" || {
  echo "error: could not create ${REPO_ROOT}/Config"
  [ "${ACTION}" = "archive" ] && exit 1
  exit 0
}

cat > "${SECRETS_FILE}" <<EOF
// Generated by ci_scripts/ci_pre_xcodebuild.sh — do not commit.
FITLOG_PROXY_SHARED_SECRET = ${FITLOG_PROXY_SHARED_SECRET}
EOF
write_status=$?
if [ "${write_status}" -ne 0 ]; then
  echo "error: failed to write ${SECRETS_FILE} (status=${write_status})"
  [ "${ACTION}" = "archive" ] && exit 1
  exit 0
fi

echo "Wrote Config/Secrets.release.xcconfig for Release Info.plist expansion (secret length=${#FITLOG_PROXY_SHARED_SECRET})."
exit 0
